### ISSUE TITLE
Verification error arduino ide

### ISSUE THREAD

**Issue by scp-electrocution** [postal2201/PSNee_V8#2]
Checking the PSNee_V8.ino file returns this error
![2022-03-19](https://user-images.githubusercontent.com/91375683/159132725-fc376fcb-eb1c-4c9a-a5eb-74f501484bcc.png)

**Comment by Kabcorp** [comment]
Make sure you are including **settings.h**

**Comment by nJoker1114** [comment]
All the headers and ino file have to use notepad to convert the encoding into ANSI before compiling.

**Comment by RastaDill** [comment]
It's not a bug. Before validate - uncomment console type in file project.
I fexed #3 this problem in prepprocessor.
