### ISSUE TITLE
Internal 8MHz Oscillator Usable?

### ISSUE THREAD

**Issue by nostalgic-indulgences** [postal2201/PSNee_V8#5]
Hi there,

I’m attempting to implement the v8 on a Japanese PM41 board using the minimum number of parts possible and have resorted to using the 8MHz internal oscillator of the ATMEGA328P-AU on a custom breakout PCB with the following fuse settings: L:C2, H:FF, E:FF. Amended the code to match the oscillator as well @ 8MHz. All my programming was done on the XGecu T56 programmer. Can’t seem to get it to work. Even original JP retail discs refuse to boot. Cd drive is working as I’m still able to play the music tracks on the game disc itself. Can you enlighten me on the feasibility of using the internal 8MHz oscillator or do I have to use an external 16MHz one strictly for bios patching? Appreciate your kind attention on this. Thank you.

**Comment by postal2201** [comment]
Hi! No, only 16MHz support.
At 8MHz the MCU speed is not enough to process the data stream.
