### ISSUE TITLE
SCPH-3500 PU-8 40 pin bios version 2.1J, region patching not working 

### ISSUE THREAD

**Issue by chris-ukk** [postal2201/PSNee_V8#8]
Hi i have a   SCPH-3500 PU-8 40 pin bios version 2.1J

region patching not working  , i use this picture for 40 pin bios -  but thats from a 1000-3000 model , there is no picture for 3500

![40pin_SCPH_1000_3000](https://github.com/postal2201/PSNee_V8/assets/172137903/aa0651fc-4979-4007-b2d5-fd92cabbaa60)

does psnee v8 suport 3500 pu-8 with 40 pin bios 2.1J  ?

CDR ntsc-j games are working 

thank you

**Comment by postal2201** [comment]
Hello!
Wrong scheme.
Try this ->
![SCPH3500_40pin](https://github.com/postal2201/PSNee_V8/assets/22731002/829f4946-ffde-47f8-8445-76958ed8e535)

**Comment by chris-ukk** [comment]
hI
Hi thanks for your reply , that does not work either
NTSC J only working  , rest do not 
![CONFIG](https://github.com/postal2201/PSNee_V8/assets/172137903/e9ecfc84-3430-49be-a238-6c11847516ad)
![FUSES](https://github.com/postal2201/PSNee_V8/assets/172137903/973b7dfc-01cd-4fa9-a502-c3581273a416)
![RESET](https://github.com/postal2201/PSNee_V8/assets/172137903/adacfdef-dc0e-4aed-b255-795431d55529)
![pic](https://github.com/postal2201/PSNee_V8/assets/172137903/11970788-7fa6-4f7e-aad1-24108eb39d50)
